---
- name: Create a complete Application Environment on AWS
  hosts: localhost
  gather_facts: false

  environment:
    AWS_REGION: "{{ target_account.region | default('eu-central-1') }}"

  pre_tasks:
    - name: Pre-tasks block
      block:
        - name: Test AWS_REGION
          shell: "[[ -n $AWS_REGION ]]"
          register: region
          failed_when: false
          changed_when: false
        - name: Test AWS_SECRET_ACCESS_KEY
          shell: "[[ -n $AWS_SECRET_ACCESS_KEY ]]"
          register: secret
          failed_when: false
          changed_when: false
        - name: Test AWS_ACCESS_KEY_ID
          shell: "[[ -n $AWS_ACCESS_KEY_ID ]]"
          register: key
          failed_when: false
          changed_when: false
        - name: Test AWS_SESSION_TOKEN
          shell: "[[ -n $AWS_SESSION_TOKEN ]]"
          register: token
          failed_when: false
          changed_when: false
        - name: Test if config file exists
          stat:
            path: "{{ configfile }}"
          register: configfilestat
          failed_when: false
          changed_when: false
        - name: Do assertions on configfile and AWS credential envvars
          assert:
            that:
              - "configfile is defined"
              - "key.rc == 0"
              - "secret.rc == 0"
              - "region.rc == 0"
              - "token.rc == 0"
              - "configfilestat.stat.exists"
        - name: Disable all alarms during playbook execution
          shell: >
            aws cloudwatch disable-alarm-actions --alarm-names $(aws cloudwatch describe-alarms --query "MetricAlarms[*].AlarmName" --output text)

      tags: [ 'always' ]

  post_tasks:
    - name: Post-tasks block
      block:
        - name: Enable all alarms after playbook execution
          shell: >
            aws cloudwatch enable-alarm-actions --alarm-names $(aws cloudwatch describe-alarms --query "MetricAlarms[*].AlarmName" --output text)

      tags: [ 'always' ]

  vars_files:
    - "{{ configfile }}"

  tasks:
    - name: Facts block
      block:
        - name: Convert project name to alpha numeric camel case
          set_fact:
            cfn_project: "{{ project.name | replace('-', ' ') | replace('.', ' ') | title | replace(' ', '') }}"
        - set_fact:
            project: "{{ project.name }}"
            shortproject: "{{ project.shortname | default(project.name) }}"
      tags: [ 'always' ]
    ### Collect info from other stacks
    - name: Get facts for the VPC stack
      cloudformation_facts:
        stack_name: "{{ referenced_stacks.VPCStackName }}"
      register: vpcfacts
      tags: [ 'always' ]
      when: "referenced_stacks is defined and referenced_stacks.VPCStackName is defined"

#    - name: Dump vpcfacts
#      debug:
#        var: vpcfacts
#      tags: [ 'always' ]

    - name: Set more variables
      set_fact:
        iam_stackname: "{{ cfn_project }}IAM"
      tags: [ 'always' ]

    - name: ECR
      block:
        - name: Create CFN template from Ansible template for the ECR Repositories
          template:
            src: "ECR.yml"
            dest: "generated-files/cfn-{{ project }}-ecr.yml"
        - name: Create or Update the ECR CloudFormation stack
          cloudformation:
            stack_name: "{{ cfn_project }}ECR"
            state: "present"
            disable_rollback: false
            template: "generated-files/cfn-{{ project }}-ecr.yml"

      when: "ecr is defined"
      tags: [ 'ecr' ]

    - name: EFS
      block:
      - name: Create CFN template from Ansible template for the EFS Filesystems
        template:
          src: "EFS.yml"
          dest: "generated-files/cfn-{{ project }}-efs.yml"
      - name: Create or Update the EFS CloudFormation stack
        cloudformation:
          stack_name: "{{ cfn_project }}EFS"
          state: "present"
          disable_rollback: false
          template: "generated-files/cfn-{{ project }}-efs.yml"

      when: "efs is defined"
      tags: [ 'efs' ]

    - name: CloudFront
      block:
      - name: Create CFN template from Ansible template for the CloudFront CDNs
        template:
          src: "CloudFront.yml"
          dest: "generated-files/cfn-{{ project }}-cloudfront.yml"
      - name: Create or Update the CloudFront CloudFormation stack
        cloudformation:
          stack_name: "{{ cfn_project }}CloudFront"
          state: "present"
          disable_rollback: false
          template: "generated-files/cfn-{{ project }}-cloudfront.yml"

      when: "cloudfront_distributions is defined"
      tags: [ 'cloudfront' ]

    - name: IAM
      block:
      - name: Create CFN template from Ansible template for the IAM resources
        template:
          src: "IAM.yml"
          dest: "generated-files/cfn-{{ project }}-iam.yml"
      - name: Create or Update the IAM Stack
        cloudformation:
          stack_name: "{{ cfn_project }}IAM"
          state: "present"
          disable_rollback: false
          template: "generated-files/cfn-{{ project }}-iam.yml"

      when: roles is defined or managed_policies is defined
      tags: [ 'iam' ]

    - name: Loadbalancers
      block:
      - name: Create template from Ansible template for the LoadBalancers
        template:
          src: "ALB.yml"
          dest: "generated-files/cfn-{{ project }}-alb-{{ item.name }}.yml"
        with_items: "{{ loadbalancers | default([]) }}"
      - name: Create or Update the Elastic LoadBalancer CloudFormation stacks
        cloudformation:
          stack_name: "{{ cfn_project }}LB{{ item.name }}"
          state: "present"
          disable_rollback: false
          template: "generated-files/cfn-{{ project }}-alb-{{ item.name }}.yml"
        register: lbstacks
        with_items: "{{ loadbalancers | default([]) }}"

      tags: [ 'ecs', 'alb' ]

    - name: Route 53
      block:
        - name: Create template from Ansible template for the Route53 Hosted Zones
          template:
            src: "Route53.yml"
            dest: "generated-files/cfn-{{ project }}-route53.yml"
        - name: Create or Update the Route53 Hosted Zones CloudFormation stacks
          cloudformation:
            stack_name: "{{ cfn_project }}Route53"
            state: "present"
            disable_rollback: false
            template: "generated-files/cfn-{{ project }}-route53.yml"

      when: route53 is defined
      tags: [ 'createstack', 'route53', 'ecs' ]

    - name: ECS Cluster
      block:
      - name: Create CFN template from Ansible template for the ECS Cluster
        template:
          src: ECS.yml
          dest: "generated-files/cfn-{{ project }}-ecs.yml"
      - name: Create or Update the ECS CloudFormation stack
        cloudformation:
          stack_name: "{{ cfn_project }}ECS"
          state: "present"
          disable_rollback: false
          template: "generated-files/cfn-{{ project }}-ecs.yml"

      when: ecs is defined
      tags: [ 'ecs' ]

    - name: S3 buckets
      block:
      - name: Create CFN template from Ansible template for project S3 buckets
        template:
          src: S3.yml
          dest: "generated-files/cfn-{{ project }}-s3.yml"
      - name: Create or Update the S3 CloudFormation stack
        cloudformation:
          stack_name: "{{ cfn_project }}S3"
          state: "present"
          disable_rollback: false
          template: "generated-files/cfn-{{ project }}-s3.yml"

      when: s3 is defined
      tags: [ 's3' ]



