---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Create a Bastion host (aws-cfn-gen version: {{ gittag | default('na') }})

### For latest ECS optimized AMIs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
Mappings:
  AWSRegionToAmzn2AMI:
    eu-central-1:
      AMIID: ami-0cc293023f983ed53
    eu-west-1:
      AMIID: ami-0bbc25e23a7640b9b
    eu-west-2:
      AMIID: ami-0d8e27447ec2c8410
    eu-west-3:
      AMIID: ami-0adcddd3324248c4c

Resources:

  BastionEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"

  BastionEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref 'BastionEC2Role']

{% if bastion.eip is defined and bastion.eip %}
  BastionEip:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref BastionHost
{% endif %}

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: false
      IamInstanceProfile: !Ref 'BastionEC2InstanceProfile'
      ImageId: !FindInMap [AWSRegionToAmzn2AMI, !Ref 'AWS::Region', AMIID]
      InstanceType: {{ bastion.instance_type | default('t2.micro') }}
      KeyName: "{{ bastion.keypair_name }}"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: {{ vpc_publicsubnet }}
          GroupSet:
            - {{ vpc_sg_dmz }}
      UserData:
        Fn::Base64: |
          Content-Type: multipart/mixed; boundary="===============8943416319660996992=="
          MIME-Version: 1.0

          --===============8943416319660996992==
          Content-Type: text/x-shellscript; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="install_sw.cloudinit"

          #!/bin/bash -xe

          yum install -y tcpdump mariadb telnet python-pip
          yum update -y

{% if bastion.pubkeys is defined or bastion.hostkeys is defined %}
          --===============8943416319660996992==
          Content-Type: text/cloud-config; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="ec2_user_pubkeys.cloudinit"

          #cloud-config
          runcmd:
{%   for key in bastion.pubkeys | default([]) %}
            - echo '{{ key.key }}' >> /home/ec2-user/.ssh/authorized_keys
{%   endfor %}
{%   if bastion.hostkeys is defined %}
            - rm -f /etc/ssh/ssh_host_*
{%   endif %}
{%   for key in bastion.hostkeys | default([]) %}
            - printf -- "{{ key.key }}" > {{ key.location }}
            - chmod 0640 {{ key.location }}
            - chown root:ssh_keys {{ key.location }}
{%   endfor %}

{% endif %}
      Tags:
        - Key: "Name"
          Value: "Bastion host"
        - Key: "Application"
          Value: "{{ application }}"
        - Key: "Environment"
          Value: "{{ env }}"

{% if bastion.route53_sns_topic is defined %}
  RecordSetForBastionHost:
    Type: Custom::IPv4
    Properties:
      ServiceToken: "{{ bastion.route53_sns_topic }}"
      Source: "{{ bastion.hostname }}.{{ bastion.domain }}"
{%   if bastion.eip is defined and bastion.eip %}
      Target: !Ref BastionEip
{%   else %}
      Target: !GetAtt BastionHost.PublicIp
{%   endif %}
      RecordType: A
{% endif %}

Outputs:
  Application:
    Value: !Ref BastionHost
    Description: The Bastion Host
    Export:
      Name: !Sub "${AWS::StackName}-BastionHost"