---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Create ECS Container Registries and a ecr-push user (aws-cfn-gen version: {{ gittag | default('na') }})

Resources:
{% for repo in ecr.repositories | default([]) %}
  {{ repo.cfn_name }}:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "{{ repo.name }}"
{%     if repo.scanonpush is defined %}
      ImageScanningConfiguration:
        ScanOnPush: true
{%     endif %}
{%     if repo.cross_account_access is defined and ( repo.cross_account_access.pull is defined or repo.cross_account_access.push is defined or repo.cross_account_access.lambda is defined) %}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
{%       if repo.cross_account_access.pull is defined %}
          -
            Sid: AllowPull
            Effect: Allow
            Principal:
              AWS:
{%         for account_id in repo.cross_account_access.pull %}
                - "arn:aws:iam::{{ account_id }}:root"
{%         endfor %}
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetAuthorizationToken"
              - "ecr:DescribeImages"
{%       endif %}
{%       if repo.cross_account_access.lambda is defined %}
          -
            Sid: AllowPullForCrossAccountLambda
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetAuthorizationToken"
              - "ecr:DescribeImages"
            Condition:
              StringLike:
                aws:sourceArn:
{%         for account_id in repo.cross_account_access.lambda %}
                  - arn:aws:lambda:eu-central-1:{{ account_id }}:function:*
{%         endfor %}
{%       endif %}
{%       if repo.cross_account_access.push is defined %}
          -
            Sid: AllowPush
            Effect: Allow
            Principal:
              AWS:
{%         for account_id in repo.cross_account_access.push %}
                - "arn:aws:iam::{{ account_id }}:root"
{%         endfor %}
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetAuthorizationToken"
              - "ecr:GetRepositoryPolicy"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:PutImage"

{%       endif %}
{%     endif %}
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
              "rules": [{
                  "rulePriority": 1,
                  "description": "Expire images older than 14 days",
                  "selection": {
                      "tagStatus": "untagged",
                      "countType": "sinceImagePushed",
                      "countUnit": "days",
                      "countNumber": 14
                  },
                  "action": {
                      "type": "expire"
                  }
              }]
          }
{% endfor %}

{% if skip_user_creation is not defined or not skip_user_creation %}
  ECRPushPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ECRPushPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource:
              - 'arn:aws:iam::{{ target_account.account_id }}:role/ECSTaskRole*'
              - 'arn:aws:iam::{{ target_account.account_id }}:role/ECSExecutionRole'
              - 'arn:aws:iam::{{ target_account.account_id }}:role/ECSExecutionRole*'
              - 'arn:aws:iam::{{ target_account.account_id }}:role/CwEvent*'
          - Action:
              - events:ListRules
              - events:ListTargetsByRule
              - events:PutTargets
              - events:DescribeRule
              - events:PutEvents
            Effect: Allow
            Resource: '*'
          - Action:
              - ecs:UpdateService
              - ecs:ListServices
              - ecs:DescribeServices
            Effect: Allow
            Resource: '*'
          - Action:
              - cloudwatch:DescribeAlarms
              - cloudwatch:DisableAlarmActions
              - cloudwatch:EnableAlarmActions
            Effect: Allow
            Resource: '*'
          - Action:
              - ecs:ListTaskDefinitionFamilies
              - ecs:RegisterTaskDefinition
              - ecs:ListTaskDefinitions
              - ecs:DescribeTaskDefinition
            Effect: Allow
            Resource: '*'
      Groups:
        - !Ref ECRPushGroup

  ECRPushGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ECRPushGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess

  ECRPush:
    Type: AWS::IAM::User
    Properties:
      UserName: ecr-push
      Groups:
        - !Ref ECRPushGroup

  ECRPullGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ECRPullGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  ECRPull:
    Type: AWS::IAM::User
    Properties:
      UserName: ecr-pull
      Groups:
        - !Ref ECRPullGroup

  KeyECRPush:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref ECRPush
{%       if iam_accesskey_serial is defined %}
      Serial: {{ iam_accesskey_serial }}
{%       endif %}

  KeyECRPull:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref ECRPull
{%       if iam_accesskey_serial is defined %}
      Serial: {{ iam_accesskey_serial }}
{%       endif %}

  ParameterStoreAccessKeyECRPush:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/{{ organization.cfn_name }}/aws-cfn-gen/ecr/ECRPush/accesskey"
      Type: String
      Value: !Ref KeyECRPush

  ParameterStoreSecretKeyECRPush:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/{{ organization.cfn_name }}/aws-cfn-gen/ecr/ECRPush/secretkey"
      Type: String
      Value: !GetAtt KeyECRPush.SecretAccessKey

  ParameterStoreAccessKeyECRPull:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/{{ organization.cfn_name }}/aws-cfn-gen/ecr/ECRPull/accesskey"
      Type: String
      Value: !Ref KeyECRPull

  ParameterStoreSecretKeyECRPull:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/{{ organization.cfn_name }}/aws-cfn-gen/ecr/ECRPull/secretkey"
      Type: String
      Value: !GetAtt KeyECRPull.SecretAccessKey


Outputs:
  AccessKeyParameterStoreNameECRPush:
    Value: !Ref ParameterStoreAccessKeyECRPush
  SecretKeyParameterStoreNameECRPush:
    Value: !Ref ParameterStoreSecretKeyECRPush
  AccessKeyParameterStoreNameECRPull:
    Value: !Ref ParameterStoreAccessKeyECRPull
  SecretKeyParameterStoreNameECRPull:
    Value: !Ref ParameterStoreSecretKeyECRPull
{% endif %}
