---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Create Lambda functions in us-east-1 for use by CloudFront Lambda@Edge (aws-cfn-gen version: {{ gittag | default('na') }})

Resources:


### Create the Lambda functinos and execution roles
{% for lambda in lambda_functions_cloudfront | default([]) %}
{#   Create some variables #}
{%   set lambda_cfn_name = lambda.name | replace('-', ' ') | replace('_', ' ') | replace('.', ' ') | title | replace(' ', '') %}
{%   set lambda_fn_name = (lambda.name.split('_'))[0] %}

  {{ lambda_cfn_name }}:
    Type: AWS::Lambda::Function
    Properties:
{%   if 'java' in lambda.runtime %}
      Handler: "{{ lambda_fn_name }}.{{ lambda.class_name | default('Handler') }}::{{ lambda.handler }}"
{%   else %}
      Handler: "{{ lambda_fn_name }}.{{ lambda.handler }}"
{% endif %}
{% if lambda.role is not defined %}
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaEdgeBasicExecutionRole"
{% else %}
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/{{ lambda.role }}"
{% endif %}
      Code:
        S3Bucket: "{{ lambda.code.s3_bucket }}"
        S3Key: "{{ lambda.code.s3_key }}"
      Runtime: {{ lambda.runtime | default('python3.12') }}
      Tags:
        - Key: Application
          Value: "{{ application }}"
        - Key: Environment
          Value: "{{ env }}"
        - Key: Customer
          Value: "{{ customer | default('NA') }}"
{% endfor %}

{# Create Lambda@Edge functions (v2)) #}
{% for lambda_edge in lambda_functions_cloudfront_v2 | default([]) %}
{#   Create some variables #}
{%   set lambda_cfn_name = lambda_edge.name | replace('-', ' ') | replace('_', ' ') | replace('.', ' ') | title | replace(' ', '') %}
  {{ lambda_cfn_name }}:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: "{{ lambda_edge.name}}"
        CodeUri: "{{ lambda_edge.code_uri }}"
        Role: "{{ lambda_edge.role_arn }}"
        Runtime: "{{ lambda_edge.runtime }}"
        Handler: "{{ lambda_edge.handler }}"
        Timeout: {{ lambda_edge.timeout | default(3) }}
        MemorySize: {{ lambda_edge.memory_size | default(128) }}
        AutoPublishAlias: live

{% endfor %}

Outputs:
{% for lambda in lambda_functions_cloudfront | default([]) %}
{#   Create some variables #}
{%   set lambda_cfn_name = lambda.name | replace('-', ' ') | replace('_', ' ') | replace('.', ' ') | title | replace(' ', '') %}

  {{ lambda_cfn_name }}Output:
    Value: !Ref {{ lambda_cfn_name }}
    Description: "Lambda function {{ lambda_cfn_name }} resource logical name"
    Export:
      Name: !Sub "${AWS::StackName}-{{ lambda_cfn_name }}"

  {{ lambda_cfn_name }}ArnOutput:
    Value: !GetAtt {{ lambda_cfn_name }}.Arn
    Description: "Lambda function {{ lambda_cfn_name }} Arn"
    Export:
      Name: !Sub "${AWS::StackName}-{{ lambda_cfn_name }}Arn"

{% endfor %}
{% for lambda in lambda_functions_cloudfront_v2 | default([]) %}
{#   Create some variables #}
{%   set lambda_cfn_name = lambda.name | replace('-', ' ') | replace('_', ' ') | replace('.', ' ') | title | replace(' ', '') %}

  {{ lambda_cfn_name }}Output:
    Value: !Ref {{ lambda_cfn_name }}
    Description: "Lambda function {{ lambda_cfn_name }} resource logical name"
    Export:
      Name: !Sub "${AWS::StackName}-{{ lambda_cfn_name }}"

  {{ lambda_cfn_name }}ArnOutput:
    Value: !GetAtt {{ lambda_cfn_name }}.Arn
    Description: "Lambda function {{ lambda_cfn_name }} Arn"
    Export:
      Name: !Sub "${AWS::StackName}-{{ lambda_cfn_name }}Arn"

  {{ lambda_cfn_name }}VersionArnOutput:
    Value: !Ref {{ lambda_cfn_name }}.Version
    Description: "Lambda function {{ lambda_cfn_name }} Version Arn"
    Export:
      Name: !Sub "${AWS::StackName}-{{ lambda_cfn_name }}VersionArn"

{% endfor %}
