Description: |
  Create all resources required to allow specified accounts to manage Route53 Resource Records in {{ item.hostedzone.domain }}

Resources:
            
  CreateRoute53CNAME:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "CreateOrUpdateRoute53RecordSet.lambda_handler"
      Role: !GetAtt CreateRoute53CNAMERole.Arn
      Runtime: python2.7
      Environment:
        Variables:
          HOSTEDZONE_ID: "{{ item.hostedzone.id }}"
      Code:
        S3Bucket: "{{ lambda_function_bucket_name }}"
        S3Key: "aws-lambda-create-or-update-route53-recordset-d2f67f9bdf0cfcac5e5c5186cd41caa86789f969.zip"

  CreateRoute53CNAMERole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns: 
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: Route53ChangeResourceRecordSets
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - route53:ChangeResourceRecordSets
            - route53:ListResourceRecordSets
            Resource: arn:aws:route53:::hostedzone/*

            
  RequestRoute53CNAME: 
    Type: AWS::SNS::Topic
    Properties:
      Subscription: 
        - Endpoint: 
            !GetAtt CreateRoute53CNAME.Arn
          Protocol: lambda
      TopicName: "RequestRoute53CNAME{{ item.hostedzone.id }}"
      
      
  RequestRoute53CNAMEPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
      - !Ref RequestRoute53CNAME
      PolicyDocument: 
        Version: 2008-10-17
        Statement:
        - Effect: Allow
          Principal: 
            AWS: [ "{{ item.allowed_accounts | json_query('[*].account_id')  | join('", "') }}" ]
          Action: 
          - sns:Publish
          Resource: !Ref RequestRoute53CNAME


  LambdaInvokePermission: 
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref RequestRoute53CNAME
      FunctionName: !GetAtt CreateRoute53CNAME.Arn

  CreateRoute53CNAMECLIRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: [ "{{ item.allowed_accounts | json_query('[*].account_id')  | join('", "') }}" ]
            Action: sts:AssumeRole
            Condition: {}
      Path: "/"
      Policies:
      - PolicyName: "Route53ChangeResourceRecordSetsCLI{{ item.hostedzone.id }}"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - route53:GetHostedZone
                - route53:ListResourceRecordSets
                - route53:ChangeResourceRecordSets
              Effect: Allow
              Resource: "arn:aws:route53:::hostedzone/{{ item.hostedzone.id }}"
            - Action:
                - route53:ListHostedZones
              Effect: Allow
              Resource: "*"
      
Outputs:
  ServiceToken:  
    Description: The arn of SNS Topic used to request a CNAME record. Share this with the subaccounts authorized to create resource records.
    Value: !Ref RequestRoute53CNAME

