---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 buckets for project {{ project }}
Resources:
{% for bucket in s3 %}
  {{ cfn_project }}{{ bucket.cfn_name }}:
    Type: AWS::S3::Bucket
    Properties:
{%   if bucket.access_control is defined and bucket.access_control in [ "AuthenticatedRead", "AwsExecRead", "BucketOwnerRead", "BucketOwnerFullControl", "LogDeliveryWrite", "Private", "PublicRead", "PublicReadWrite" ] %}
      AccessControl: {{ bucket.access_control }}
{%   else %}
      AccessControl: Private
{%   endif %}
      BucketName: "{{ application }}-{{ env }}-{{ bucket.name }}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
{%   if bucket.versioning is defined %}
      VersioningConfiguration:
        Status: {{ bucket.versioning | lower | title }}
{%   endif %}
      LifecycleConfiguration:
{%   if bucket.lifecycle_configuration is not defined %}
        Rules:
          - NoncurrentVersionExpirationInDays: 60
            Status: Enabled
{%   else %}
{%     for line in bucket.lifecycle_configuration.split('\n') %}
        {{ line }}
{%     endfor %}
{%   endif %}
{%   if bucket.static_website_hosting is defined and ( bucket.static_website_hosting or bucket.static_website_hosting in [ "yes", "Yes", "true", "True", "on", "On" ] ) %}
      WebsiteConfiguration:
        IndexDocument: {{ bucket.indexdocument | default('index.html') }}
        ErrorDocument: {{ bucket.errordocument | default('error.html') }}
{%   endif %}
      Tags:
      - Key: Application
        Value: "{{ application }}"
      - Key: Environment
        Value: "{{ env }}"
      - Key: Customer
        Value: "{{ customer | default('NA') }}"

{% endfor %}

{% if s3_policies is defined %}
{%   for policy in s3_policies %}
{# It's not very useful to create a BucketPolicy without a policy document #}
{%     if policy.policy_document is defined %}
  {{ cfn_project }}{{ policy.cfn_name }}:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - {{ cfn_project }}{{ policy.bucket_cfn_name }}
    Properties:
      Bucket: !Ref {{ cfn_project }}{{ policy.bucket_cfn_name }}
      PolicyDocument:
        {{ policy.policy_document | to_json }}
{%     endif %}
{%   endfor %}
{% endif %}
