---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Create VPC Endpoints for project {{ project }} (aws-cfn-gen version: {{ gittag | default('na') }})
Resources:

  VPCEndpointS3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: "{{ vpc_id }}"
      RouteTableIds:
        - "{{ vpc_privatesubnet_routetable }}"
        - "{{ vpc_publicsubnet_routetable }}"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"

{% for ep in vpc_interface_endpoints | default[] %}
  VPCEndpoint{{ ep.cfn_name }}:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
{%   for sg_import in ep.sg_imports %}
        - !ImportValue {{ sg_import }}
{%   endfor %}
      ServiceName: {{ ep.aws_service }}
      SubnetIds:
{%   for subnet_import in ep.subnet_imports %}
        - !ImportValue {{ subnet_import }}
{%   endfor %}
      VpcEndpointType: Interface
      VpcId: !ImportValue {{ ep.vpc_import }}
{% endfor %}
